# Generated by Django 3.2.12 on 2024-03-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
